#!/usr/bin/env python3
"""
Altium ASCII Format Exporter
==============================

Altium Designer supports ASCII format for SchDoc files!
This allows us to export to text-based format that can be:
1. Easily edited
2. Version controlled
3. Re-imported to Altium

Usage:
    File > Save As > "Advanced Schematic ascii(*.SchDoc)"

This script converts our parsed data to Altium ASCII format.
"""

from altium_parser import AltiumParser
from altium_objects import *
from typing import List, Dict


class AltiumAsciiExporter:
    """
    Export SchDoc to Altium ASCII format.

    Altium ASCII format is a text-based representation where each
    object is represented as a record with pipe-delimited properties.
    """

    def __init__(self):
        pass

    def export_to_ascii(self, doc: SchDoc, filename: str):
        """
        Export SchDoc to Altium ASCII format.

        Args:
            doc: Parsed SchDoc document
            filename: Output ASCII file path
        """

        lines = []

        # Add header comment
        lines.append(";")
        lines.append("; Altium Designer Schematic ASCII File")
        lines.append("; Generated by altium_schdoc_editor")
        lines.append(";")
        lines.append("")

        # Export all objects
        for obj in doc.objects:
            # Each object is a single line with pipe-delimited properties
            line = self._object_to_ascii(obj)
            if line:
                lines.append(line)

        # Write to file
        with open(filename, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))

        print(f"✓ ASCII 파일 생성: {filename}")
        print(f"  - {len(doc.objects)}개 객체 내보냄")
        print(f"  - {len(lines)}줄")

    def _object_to_ascii(self, obj: AltiumObject) -> str:
        """
        Convert an object to ASCII format line.

        Format: |PROPERTY=value|PROPERTY=value|...
        """

        # Use stored properties if available (preserves original format)
        if obj.properties:
            parts = []
            for key, value in sorted(obj.properties.items()):
                # Escape special characters
                value_escaped = str(value).replace('|', '\\|')
                parts.append(f"{key}={value_escaped}")

            return '|' + '|'.join(parts) + '|'

        return ""

    def export_with_modifications(self, doc: SchDoc, filename: str,
                                  junctions_to_add: List[tuple]):
        """
        Export with modifications (e.g., added junctions).

        Args:
            doc: Original document
            filename: Output file
            junctions_to_add: List of (x, y) coordinates for new junctions
        """

        # Create modified copy
        import copy
        doc_modified = copy.deepcopy(doc)

        # Add junctions
        next_index = max(obj.index for obj in doc_modified.objects) + 1

        for i, (x, y) in enumerate(junctions_to_add):
            junction = Junction()
            junction.index = next_index + i
            junction.location_x = x
            junction.location_y = y
            junction.color = 0x000000
            junction.owner_part_id = -1
            junction.unique_id = self._generate_uid()

            # Create properties for ASCII export
            junction.properties = {
                'RECORD': '29',  # Junction record type
                'LOCATION.X': str(x),
                'LOCATION.Y': str(y),
                'COLOR': str(junction.color),
                'OWNERPARTID': str(junction.owner_part_id),
                'UNIQUEID': junction.unique_id
            }

            doc_modified.objects.append(junction)

        # Export
        self.export_to_ascii(doc_modified, filename)

        print(f"✓ {len(junctions_to_add)}개 접속점 추가됨")

    def _generate_uid(self) -> str:
        """Generate Altium-style unique ID"""
        import random
        chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        return ''.join(random.choice(chars) for _ in range(8))


def main():
    """
    Main function - demonstrate ASCII export
    """

    print("""
╔════════════════════════════════════════════════════════════════════════════╗
║                                                                            ║
║              Altium ASCII Format Exporter                                  ║
║                                                                            ║
║  Altium Designer는 ASCII 텍스트 형식을 지원합니다!                        ║
║  이를 통해 쉽게 편집하고 다시 Altium에서 열 수 있습니다.                  ║
║                                                                            ║
╚════════════════════════════════════════════════════════════════════════════╝
    """)

    # Parse original file
    print("\n📂 DI.SchDoc 파싱 중...")
    parser = AltiumParser()
    doc = parser.parse_file("DI.SchDoc")
    print(f"✓ 파싱 완료: {len(doc.objects)}개 객체")

    # Export to ASCII
    exporter = AltiumAsciiExporter()

    print("\n📝 ASCII 형식으로 내보내기...")
    exporter.export_to_ascii(doc, "DI_ascii.txt")

    print("\n" + "=" * 70)
    print("✨ ASCII 파일 생성 완료!")
    print("=" * 70)

    print("""
다음 단계:

방법 1: 텍스트 편집기로 수정
  1. DI_ascii.txt 파일을 텍스트 에디터로 열기
  2. 접속점 추가 (RECORD=29 라인 추가)
  3. 저장
  4. Altium Designer에서 열기

방법 2: 자동으로 접속점 추가
  아래 스크립트 참조:
    """)

    # Show example of adding junctions
    print("\n" + "=" * 70)
    print("📋 접속점 추가 예제")
    print("=" * 70)

    # Load junction list from analysis
    import json
    try:
        with open('DI_analysis_report.json', 'r', encoding='utf-8') as f:
            report = json.load(f)

        # Extract junction coordinates from issues
        junctions = []
        for issue in report.get('issues', []):
            if '접속점 누락' in issue and '(' in issue:
                coords = issue.split('(')[1].split(')')[0]
                x, y = coords.split(',')
                junctions.append((int(x.strip()), int(y.strip())))

        if junctions:
            print(f"\n발견된 접속점: {len(junctions)}개")
            print("\n접속점이 추가된 ASCII 파일 생성 중...")

            exporter.export_with_modifications(
                doc,
                "DI_with_junctions_ascii.txt",
                junctions
            )

            print("\n✅ 완료!")
            print(f"   파일: DI_with_junctions_ascii.txt")
            print(f"   접속점: {len(junctions)}개 추가")

    except Exception as e:
        print(f"(분석 보고서를 찾을 수 없음: {e})")

    print("""
=" * 70)
🎯 Altium Designer에서 사용하기
=" * 70)

1. Altium Designer 열기
2. File > Open > DI_with_junctions_ascii.txt 선택
3. 파일이 열림 (모든 수정사항 포함!)
4. File > Save As > .SchDoc 바이너리 형식으로 저장

주의사항:
- ASCII 파일은 텍스트 형식이므로 쉽게 편집 가능
- 하지만 정확한 형식을 따라야 함
- 생성된 파일을 Altium에서 검증 필요

장점:
✅ 텍스트 기반 - 쉽게 편집
✅ 버전 관리 가능 (Git 등)
✅ 프로그래밍 방식 수정 가능
✅ Altium에서 다시 열림
✅ OLE 파일 문제 없음!
    """)


if __name__ == "__main__":
    main()
